#! /bin/bash
nasm -felf -g -o calcularApariciones.o bmp2oc2/calcularApariciones.asm
nasm -felf -g -o armarTablaCodigos.o bmp2oc2/armarTablaCodigos.asm
nasm -felf -g -o codificar.o bmp2oc2/codificar.asm
nasm -felf -g -o decodificar.o oc22bmp/decodificar.asm
gcc -c -g bmp2oc2/bmp2oc2.c
gcc -c -g oc22bmp/oc22bmp.c

gcc -g -o run_bmp2oc2 bmp2oc2.o calcularApariciones.o armarTablaCodigos.o codificar.o
gcc -g -o run_oc22bmp oc22bmp.o decodificar.o
rm *.o
