#! /bin/bash
# yasm -felf -gdwarf2 -o calcularApariciones.o bmp2oc2/calcularApariciones.asm
# yasm -felf -gdwarf2 -o armarTablaCodigos.o bmp2oc2/armarTablaCodigos.asm
# yasm -felf -gdwarf2 -o codificar.o bmp2oc2/codificar.asm
# yasm -felf -gdwarf2 -o decodificar.o oc22bmp/decodificar.asm
gcc -c -g bmp2joc2/bmp2joc2.c
# gcc -c -g oc22bmp/oc22bmp.c

gcc -g -o run_bmp2joc2 bmp2joc2.o # calcularApariciones.o armarTablaCodigos.o codificar.o
# gcc -g -o run_oc22bmp oc22bmp.o decodificar.o
rm *.o
