#! /bin/bash

if [ $# -eq 0 ]  # El script tiene que tener al menos un parametro.
then
  echo "Modo de uso:
		$0 <Imagen.jocd>
		Devuelve: Imagen-rev.bmp"
  exit $E_NO_ARGS
fi  

decompresor="compresion/run_oc22bmp"
compiladorDecompresor="compresion/compilar"
if [ ! -f $compresor ]  # El script tiene que tener al menos un parametro.
then
	if [ ! -f $compiladorDecompresor ]  # El script tiene que tener al menos un parametro.
	then
		echo "Fatal Error: faltan archivos para generar el decompresor"
		exit
	else
		cd compresion
		./compilar
		cd ../
	fi
fi

if [ ! -f $1 ]  # El archivo por parametro no existe.
then
	echo "Archivo inexistente"
	exit
fi

inFile=${1%.*}
tempOutFile=temp_${inFile##*/}_decompressed.joc2
./compresion/run_oc22bmp $1 $tempOutFile
./run_joc22bmp $tempOutFile $inFile-rev.bmp deluxe
if [ -f $tempOutFile ]
then
	rm $tempOutFile
fi
