#! /bin/bash
yasm -felf -gdwarf2 -o dividir.o bmp2joc2/dividir.asm
yasm -felf -gdwarf2 -o generardct.o bmp2joc2/generardct.asm

gcc -c -g -m32 bmp2joc2/bmp2joc2.c

gcc -g -m32 -multilib -o run_bmp2joc2 bmp2joc2.o dividir.o generardct.o -lm

rm *.o
